# Generated by Django 4.2.4 on 2023-08-27 04:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("TicketPal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="buyNow",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="bidders",
            field=models.ManyToManyField(
                blank=True,
                related_name="tickets_as_bidders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="maxBidder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_as_max_bidder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
